.vscode/launch.json, .vscode/settings.json, index.ts, package-lock.json, package.json, spec/bugsplat-api-client.e2e.ts, spec/bugsplat-api-client.spec.ts, spec/support/jasmine.e2e.json, spec/support/jasmine.json, spec/support/jasmine.spec.json, src/bugsplat-api-client.ts, tsconfig.esm.json, tsconfig.json
Adds BugSplatApiClient and login method. Adds tests and test configs. Adds support Jasmine Test Explorer extension in VS Code.
=> Adds TypeScript

package.json, tsconfig.json
Adds sourceMap to tsconfig.json. Adds watch:cjs and watch:esm commands.
=> Adds debugging helpers

package.json, src/common/index.ts, src/crash/index.ts
=> Fixes Package can't be imported in Angular project

package-lock.json, package.json, spec/support/jasmine.teamcity.e2e.json, spec/support/jasmine.teamcity.spec.json, spec/support/teamcity.ts
=> Fixes Add TeamCity Support #16

spec/config.ts, src/common/bugsplat-api-client.e2e.ts, src/crash/crash-api-client/crash-api-client.e2e.ts, src/events/events-api-client/events-api-client.e2e.ts
=> Removes sensitive value from e2e tests

spec/fakes/common/response.ts, src/common/bugsplat-api-client.spec.ts, src/crash/crash-api-client/crash-api-client.e2e.ts, src/crash/crash-api-client/crash-api-client.spec.ts, src/crash/crash-api-client/crash-api-client.ts, src/events/events-api-client/events-api-client.spec.ts
=> Fixes Add reprocessCrash to CrashApiClient #20

src/crash/crash-details/crash-details.spec.ts, src/events/event-stream/event-stream-event.ts, src/events/event/event.spec.ts, src/events/event/event.ts, src/events/events-api-client/events-api-client.e2e.ts
=> Fixes Events comment event comment property should be message #24

spec/fakes/crash/crash-api-response.ts, spec/fakes/events/events.ts, src/events/event-stream/event-stream-event.ts, src/events/event-stream/event-stream-id.ts, src/events/event/create-event-from-api-response.spec.ts, src/events/event/create-event-from-api-response.ts, src/events/event/event.spec.ts, src/events/event/event.ts, src/events/events-api-client/events-api-client.ts, src/events/index.ts
=> Add support for defect events #26

package-lock.json, package.json, spec/fakes/common/response.ts, src/index.ts, src/symbols/exists.ts, src/symbols/index.ts, src/symbols/s3-api-client/s3-api-client.spec.ts, src/symbols/s3-api-client/s3-api-client.ts, src/symbols/symbols-api-client/symbols-api-client.e2e.ts, src/symbols/symbols-api-client/symbols-api-client.spec.ts, src/symbols/symbols-api-client/symbols-api-client.ts
=> Adds symbol post and delete support

README.md, src/common/bugsplat-api-client.spec.ts, src/common/bugsplat-api-client.ts, src/common/environment.ts, src/crash/crash-api-client/crash-api-client.e2e.ts, src/events/events-api-client/events-api-client.e2e.ts, src/symbols/symbols-api-client/symbols-api-client.e2e.ts
Updates README.md to explain caveats between authentication in Node.js and Web Browser environments.
Fixes #18
=> Adds convenience functions for authenticating

package-lock.json, package.json, tsconfig.cjs.json, tsconfig.json
=> Fixes Paths in generated output are wrong #44

src/common/client/oauth-client-credentials-api-client/oauth-client-credentials-api-client.e2e.ts
=> Fixes broken e2e tests

src/common/client/index.ts
=> Adds export for OAuthClientCredentialsClient

src/common/file/bugsplat-file.ts
=> fix: Adds Buffer to UploadableFile union type

.commitlintrc.js, .github/workflows/release.yml, .husky/commit-msg, .husky/pre-commit, package-lock.json, package.json
=> chore: automate npm release

package-lock.json, spec/fakes/common/response.ts, src/common/client/bugsplat-api-client/bugsplat-api-client.e2e.ts, src/common/client/bugsplat-api-client/bugsplat-api-client.spec.ts, src/common/client/bugsplat-api-client/bugsplat-api-client.ts, src/common/client/oauth-client-credentials-api-client/oauth-client-credentials-api-client.e2e.ts, src/common/client/oauth-client-credentials-api-client/oauth-client-credentials-api-client.spec.ts, src/common/client/oauth-client-credentials-api-client/oauth-client-credentials-api-client.ts, src/crash/crash-api-client/crash-api-client.spec.ts, src/events/events-api-client/events-api-client.spec.ts
=> fix: throw more useful error if OAuthClientCredentialsApiClient fails to authenticate

src/common/data/table-data/index.ts
=> fix: expose TableDataFormDataBuilder

src/crashes/crashes-api-row/crashes-api-row.ts
=> fix: crashesApiRow id, stackKeyId should be type number

src/crashes/crashes-api-client/crashes-api-client.e2e.ts, src/crashes/crashes-api-row/crashes-api-row.ts
=> fix: add groupByCount to CrashesApiRow

.github/workflows/release.yml, package-lock.json, package.json
Also updates release workflow to use node 16.x.
=> fix: fix security issues

package-lock.json, src/versions/versions-api-row/versions-api-row.ts
Fixed incorrect parsing of Versions API response
=> fix: set retired and fullDumps correctly

package-lock.json, package.json, spec/fakes/common/response.ts, spec/files/native/post-native-crash.ts, src/common/client/api-client.ts, src/common/client/bugsplat-api-client/bugsplat-api-client.spec.ts, src/common/client/bugsplat-api-client/bugsplat-api-client.ts, src/common/client/bugsplat-api-client/bugsplat-login-response.ts, src/common/client/oauth-client-credentials-api-client/oauth-client-credentials-api-client.spec.ts, src/common/client/oauth-client-credentials-api-client/oauth-client-credentials-api-client.ts, src/common/client/oauth-client-credentials-api-client/oauth-login-response.ts, src/common/data/table-data/table-data-client/table-data-client.ts, src/common/data/table-data/table-data-client/table-data-response.ts, src/crash/crash-api-client/crash-api-client.ts, src/crash/crash-details/crash-details.ts, src/crashes/crashes-api-client/crashes-api-client.ts, src/events/events-api-client/events-api-client.ts, src/post/crash-post-client.e2e.ts, src/post/crash-post-client.ts, src/post/post-crash-response.ts, src/summary/summary-table-data/summary-table-data-client.ts, src/versions/versions-api-client/put-retired-response.ts, src/versions/versions-api-client/versions-api-client.e2e.ts, src/versions/versions-api-client/versions-api-client.ts
* Allow json body reuse
* Safer type for BugSplatResponse
BREAKING CHANGE: ApiClients now return Response so they can be cloned, BugSplatResponse json property is no longer type any.
=> feat!: allow body reuse

package-lock.json, package.json, spec/files/native/post-native-crash.ts, src/common/client/bugsplat-api-client/bugsplat-api-client.ts, src/common/client/oauth-client-credentials-api-client/oauth-client-credentials-api-client.e2e.ts, src/common/client/oauth-client-credentials-api-client/oauth-client-credentials-api-client.ts, src/common/client/s3-api-client/s3-api-client.ts, src/common/data/table-data/table-data-client/table-data-client.ts, src/crash/crash-api-client/crash-api-client.e2e.ts, src/crash/crash-api-client/crash-api-client.ts, src/crash/crash-details/crash-details.ts, src/crashes/index.ts, src/crashes/key-crash-api-client/key-crash-api-client.e2e.ts, src/crashes/key-crash-api-client/key-crash-api-client.spec.ts, src/crashes/key-crash-api-client/key-crash-api-client.ts, src/crashes/key-crash-api-client/key-crash-table-data-request.ts, src/post/crash-post-client.ts, src/summary/summary-table-data/summary-table-data-client.ts, src/versions/versions-api-client/versions-api-client.ts, tsconfig.json
* Add Key Crash client
* Add duplex 'half' to request inits to satisfy new fetch spec
Depends on https://github.com/BugSplat-Git/webroot/pull/856
=> feat: add key crash client

.vscode/launch.json, src/versions/index.ts, src/versions/versions-api-client/symbol-file.ts, src/versions/versions-api-client/versions-api-client.ts
Changes to support uploading with bsv1 protocol via symbol-upload
=> fix: symbol upload moduleName

spec/fakes/crash/crash-api-response.ts, src/common/parse.ts, src/crash/crash-details/crash-details.spec.ts, src/crash/crash-details/crash-details.ts, src/crashes/crashes-api-row/crashes-api-row.ts
Support for attributes in Crashes, Key Crash, and Crash endpoints.
=> feat: attributes

package-lock.json, package.json, spec/files/native/post-native-crash.ts, src/common/delay.ts, src/crash/additional-info/additional-info.spec.ts, src/crash/additional-info/additional-info.ts, src/post/crash-post-client.e2e.ts, src/summary/summary-api-client/summary-api-client.e2e.ts, src/symbols/symbols-api-client/symbols-api-client.spec.ts, src/symbols/symbols-api-client/symbols-api-client.ts, src/versions/versions-api-client/versions-api-client.spec.ts, src/versions/versions-api-client/versions-api-client.ts
* Gracefully handle missing additional info prop
* Remove rxjs dependency
=> fix: handle missing additional info

src/common/client/api-client.ts, src/common/client/bugsplat-api-client/bugsplat-api-client.ts, src/common/client/index.ts, src/common/client/oauth-client-credentials-api-client/oauth-client-credentials-api-client.ts
Helps us fix a bug where symbol-upload retries after auth failure.
=> feat: better hook for handling auth errors

package-lock.json, package.json, src/symbols/symbols-api-client/symbols-api-client.spec.ts, src/symbols/symbols-api-client/symbols-api-client.ts, src/versions/versions-api-client/versions-api-client.ts
Fix a memory leak where we teed a stream, but didn't cancel the slowest reader when we were done with it. Also added explicit closing of the teed streams in hopes that it will cause the original stream to get cleaned up as well.
=> fix: leaky symbol upload streams

src/crash/crash-details/crash-details.ts
Added type for Monday.com used in our web app.
=> feat: defect tracker type for monday.com

src/crash/crash-details/crash-details.ts
Add GitLab defect tracker option for web app.
=> feat: add gitlab defect tracker type

src/crash/crash-details/crash-details.ts
Add DefectTrackerType Favro for web app.
=> feat: add favro support

src/common/data/table-data/table-data-client/table-data-client.ts, src/crashes/crashes-api-client/crashes-api-client.spec.ts, src/crashes/crashes-api-client/crashes-api-client.ts
Updates to new api/crashes endpoint which supports DELETE for ids.
=> feat: delete crashes

src/post/crash-type.ts
=> fix: add ps4/ps5 crash types

src/symbols/symbols-api-client/symbols-api-client.ts
Use ISO string for lastModified.
=> fix: last modified date format

.github/workflows/test.yml, package.json
=> chore: migrate PR protection to GH actions
